language: cpp
os: linux
dist: xenial

matrix:
  include:

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER="clang++"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++11 -Wno-c++1z-extensions"

    - os: osx
      osx_image: xcode12.2
      compiler: clang
      env:
        - COMPILER="clang++"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++17 -DLIBCPP_TEST_DEDUCTION_GUIDES"

    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-4.9
      env:
        - COMPILER="g++-4.9"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++11"

    - compiler: gcc
      # gcc 5.4.0
      env:
        - COMPILER="g++"
        - BUILD_TYPE="Debug"
        - CXXFLAGS="-std=c++17"

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER="g++-7"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++17 -DMOMO_USE_SAFE_MAP_BRACKETS -DMOMO_USE_UNORDERED_HINT_ITERATORS"

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - COMPILER="g++-9"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++17 -DLIBCPP_TEST_DEDUCTION_GUIDES"

    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
      env:
        - COMPILER="clang++-3.6"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++11"

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0
      env:
        - COMPILER="clang++-5.0"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++17 -DMOMO_USE_SAFE_MAP_BRACKETS -DMOMO_USE_UNORDERED_HINT_ITERATORS"

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - COMPILER="clang++-8"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-std=c++17 -DLIBCPP_TEST_DEDUCTION_GUIDES"

    - compiler: clang
      # clang 7.0.0
      env:
        - COMPILER="clang++"
        - BUILD_TYPE="Debug"
        - CXXFLAGS="-std=c++17 -fsanitize=address,undefined -DLIBCPP_TEST_DEDUCTION_GUIDES"

script:
  - cd test
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make VERBOSE=1
  - ./momo_test
