language: cpp
os: linux

script:
  - cd test
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - ./momo_test

matrix:
  include:

    - compiler: clang
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
      env:
        - COMPILER="clang++-10"
        - BUILD_TYPE="Debug"
        - CXXFLAGS="-msse2 -fsanitize=address,undefined"

    - compiler: gcc
      dist: bionic
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-msse2"

    - compiler: gcc
      arch: arm64
      dist: bionic
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Debug"
        - CXXFLAGS=""

    - compiler: gcc
      arch: ppc64le
      dist: bionic
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-DMOMO_USE_SAFE_MAP_BRACKETS"

    - compiler: gcc
      arch: s390x
      dist: bionic
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-DMOMO_USE_UNORDERED_HINT_ITERATORS"
