language: cpp
os: linux
dist: bionic

script:
  - cd test
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - ./momo_test

matrix:
  include:

#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
#              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
#          packages:
#            - g++-10
#            - clang-11
#      env:
#        - COMPILER="clang++-11"
#        - BUILD_TYPE="Debug"
#        - CXXFLAGS="-msse2 -fsized-deallocation -fsanitize=address,undefined"

    - compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-msse2"

    - compiler: gcc
      arch: arm64
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Debug"
        - CXXFLAGS=""

    - compiler: gcc
      arch: ppc64le
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-DMOMO_USE_SAFE_MAP_BRACKETS"

    - compiler: gcc
      arch: s390x
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-10
      env:
        - COMPILER="g++-10"
        - BUILD_TYPE="Release"
        - CXXFLAGS="-DMOMO_USE_UNORDERED_HINT_ITERATORS"
