name: Clang

on:
  push:
    branches:
      - '**'

jobs:
  momo-test:
    strategy:
      matrix:
        include:

        # x64
        - clang_ver: '19'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++23 -Werror'
          cont_ver: '26.04'

        - clang_ver: '20'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04'
          build_type: 'Debug'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror -fsanitize=address,undefined'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'On'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'On'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

        # ARM64
        - clang_ver: '19'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++23 -Werror'
          cont_ver: '26.04'

        - clang_ver: '20'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04-arm'
          build_type: 'Debug'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror -fsanitize=address,undefined'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'On'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

        - clang_ver: '21'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'On'
          flags: '-std=c++26 -Werror'
          cont_ver: '26.04'

    runs-on: ubuntu-${{ matrix.ubuntu_ver }}
    container: ubuntu:${{ matrix.cont_ver }}

    steps:
    - name: Install tools
      run: |
        apt-get update
        apt-get install -y cmake
        apt-get install -y ninja-build
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install Clang
      run: apt-get install -y clang-${{ matrix.clang_ver }}
    - name: Build
      env:
        CXX: clang++-${{ matrix.clang_ver }}
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DMOMO_TEST_NO_EXCEPTIONS_RTTI=${{ matrix.no_exceptions_rtti }} \
          -DMOMO_TEST_EXTRA_SETTINGS=${{ matrix.extra_settings }}
        cmake --build . -v
    - name: Test
      run: test/build/momo_test
