name: GCC

on:
  push:
    branches:
      - '**'

jobs:
  momo-test:
    strategy:
      matrix:
        include:

        # x64
        - gcc_ver: '15'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++23'

        - gcc_ver: '15'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - gcc_ver: '15'
          ubuntu_ver: '24.04'
          build_type: 'Debug'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror'

        - gcc_ver: '15'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'On'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - gcc_ver: '15'
          ubuntu_ver: '24.04'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'On'
          flags: '-std=c++26'

        # ARM64
        - gcc_ver: '15'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++23 -Wno-psabi'

        - gcc_ver: '15'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Wno-psabi'

        - gcc_ver: '15'
          ubuntu_ver: '24.04-arm'
          build_type: 'Debug'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26 -Werror -Wno-psabi -mcmodel=large'

        - gcc_ver: '15'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'On'
          extra_settings: 'Off'
          flags: '-std=c++26 -Wno-psabi'

        - gcc_ver: '15'
          ubuntu_ver: '24.04-arm'
          build_type: 'Release'
          no_exceptions_rtti: 'Off'
          extra_settings: 'On'
          flags: '-std=c++26 -Wno-psabi'

    runs-on: ubuntu-${{ matrix.ubuntu_ver }}

    steps:
#    - uses: actionhippie/swap-space@v1 # 10G
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup GCC
      uses: egor-tensin/setup-gcc@v2
      with:
        version: ${{ matrix.gcc_ver }}
#    - name: Install GCC
#      run: sudo apt install g++-${{ matrix.gcc_ver }}
    - name: Build
      env:
        CXX: g++-${{ matrix.gcc_ver }}
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DMOMO_TEST_NO_EXCEPTIONS_RTTI=${{ matrix.no_exceptions_rtti }} \
          -DMOMO_TEST_EXTRA_SETTINGS=${{ matrix.extra_settings }}
        cmake --build . -v
    - name: Test
      run: test/build/momo_test
