name: IntelLLVM

on: [push, pull_request]

jobs:
  momo-test:
    strategy:
      matrix:
        include:

        - build_type: 'Release'
          flags: '-std=c++11 -Werror -msse2'

        - build_type: 'Release'
          flags: '-std=c++11 -Werror -fno-rtti -DMOMO_USE_SAFE_MAP_BRACKETS -DMOMO_USE_UNORDERED_HINT_ITERATORS -DMOMO_DISABLE_TYPE_INFO'

        - build_type: 'Release'
          flags: '-std=c++14 -Werror -msse2'

        - build_type: 'Release'
          flags: '-std=c++17 -Werror -msse2'

        - build_type: 'Release'
          flags: '-std=c++20 -Werror -msse2 -DTEST_LIBCXX_NEW'

        - build_type: 'Release'
          flags: '-std=c++20 -Werror -DTEST_LIBCXX_NEW -fno-rtti -DMOMO_USE_SAFE_MAP_BRACKETS -DMOMO_USE_UNORDERED_HINT_ITERATORS -DMOMO_DISABLE_TYPE_INFO'

        - build_type: 'Debug'
          flags: '-std=c++20 -Werror -msse2 -DTEST_LIBCXX_NEW'

        - build_type: 'Debug'
          flags: '-std=c++20 -Werror -DTEST_LIBCXX_NEW -fno-rtti -DMOMO_USE_SAFE_MAP_BRACKETS -DMOMO_USE_UNORDERED_HINT_ITERATORS -DMOMO_DISABLE_TYPE_INFO'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Install Intel
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV
    - name: Build
      env:
        CXX: icpx
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build . -v
    - name: Test
      run: test/build/momo_test
