name: Lines of code

on: [push, pull_request]

jobs:
  calc-loc:
    strategy:
      matrix:
        include:

        - dir: '.'

        - dir: './include'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Calculate LOC
      id: loc
      uses: PavanMudigonda/lines-of-code-reporter@v1.6
      with:
        directory: ${{ matrix.dir }}
        skip_check_run: true
