name: MinGW

on:
  push:
    branches:
      - '**'

jobs:
  momo-test:
    strategy:
      matrix:
        include:

        # x64
        - arch: 'x64'
          build_type: 'Release'
          test_libcxx20: 'Off'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++11'

        - arch: 'x64'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - arch: 'x64'
          build_type: 'Debug'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - arch: 'x64'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'On'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - arch: 'x64'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'On'
          flags: '-std=c++26'

        # x86
        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'Off'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++11'

        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'Off'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++14'

        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'Off'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++17'

        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++20'

        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++23'

        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - arch: 'x86'
          build_type: 'Debug'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'On'
          extra_settings: 'Off'
          flags: '-std=c++26'

        - arch: 'x86'
          build_type: 'Release'
          test_libcxx20: 'On'
          no_exceptions_rtti: 'Off'
          extra_settings: 'On'
          flags: '-std=c++26'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
#    - name: Install Ninja
#      run: choco install ninja
    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v3
      with:
        platform: ${{ matrix.arch }}
    - name: Build
      env:
        CXX: g++
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
          -DMOMO_TEST_LIBCXX20=${{ matrix.test_libcxx20 }} `
          -DMOMO_TEST_NO_EXCEPTIONS_RTTI=${{ matrix.no_exceptions_rtti }} `
          -DMOMO_TEST_EXTRA_SETTINGS=${{ matrix.extra_settings }}
        cmake --build . -v
    - name: Test
      run: test/build/momo_test.exe
