name: C++/CLI

on: [push, pull_request]

jobs:
  momo-test:
    strategy:
      matrix:
        include:

        # Visual Studio 2019
        - win_ver: '2019'
          build_type: 'Release'
          flags: '/std:c++17 /WX'

    runs-on: windows-${{ matrix.win_ver }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      env:
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake .. -DMOMO_TEST_MSVC_CLI=On -DCMAKE_VERBOSE_MAKEFILE=On
        cmake --build . --config ${{ matrix.build_type }}
#    - name: Test
#      run: test/build/${{ matrix.build_type }}/momo_test.exe
