name: C++/CLI

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  momo-test:
    strategy:
      matrix:
        include:

        # Visual Studio 2022
        - toolset: '14.4'
          build_type: 'Release'
          test_libcxx20: 'Off'
          flags: '/std:c++20 /WX'
          win_ver: '2025'

    runs-on: windows-${{ matrix.win_ver }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: ${{ matrix.toolset }}
    - name: Build
      env:
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake .. -DMOMO_TEST_MSVC_CLI=On `
          -DMOMO_TEST_LIBCXX20=${{ matrix.test_libcxx20 }} `
          -DCMAKE_VERBOSE_MAKEFILE=On
        cmake --build . --config ${{ matrix.build_type }}
#    - name: Test
#      run: test/build/${{ matrix.build_type }}/momo_test.exe
