name: C++/CLI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:

        # Visual Studio 2022
        - win_ver: '2022'
          build_type: 'Release'
          flags: '/clr /std:c++17 /WX /Zc:__cplusplus /DLIBCPP_TEST_DEDUCTION_GUIDES'

        - win_ver: '2022'
          build_type: 'Debug'
          flags: '/clr /std:c++17 /WX /Zc:__cplusplus /DLIBCPP_TEST_DEDUCTION_GUIDES'

    runs-on: windows-${{ matrix.win_ver }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      env:
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake ..
        cmake --build . --config ${{ matrix.build_type }}
#    - name: Test
#      run: test/build/${{ matrix.build_type }}/momo_test.exe
