name: C++/CLI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:

        # Visual Studio 2022
        - win_ver: '2022'
          build_type: 'Release'
          flags: '/clr /std:c++17 /WX /Zc:__cplusplus /DLIBCPP_TEST_DEDUCTION_GUIDES'
          arch: 'x64'

    runs-on: windows-${{ matrix.win_ver }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Setup MSVC
      uses: egor-tensin/vs-shell@v2
      with:
        arch: ${{ matrix.arch }}
    - name: Build
      env:
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        cd test
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build . -v
#    - name: Test
#      run: test/build/momo_test.exe
