name: Perf Clang

on: [push, pull_request]

jobs:
  momo-perf:
    strategy:
      matrix:
        include:
        
        - type: 'unordered_map'
          clang_ver: '19'

        - type: 'unordered_map_open'
          clang_ver: '19'

        - type: 'map'
          clang_ver: '19'

        - type: 'data_table_static'
          clang_ver: '19'

    # ARM64
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout hash-table-shootout
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/hash-table-shootout'
        ref: 'regress'
    - name: Checkout momo_v3_2
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.2'
        path: 'momo_v3_2'
    - name: Checkout momo_v3_5
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.5'
        path: 'momo_v3_5'
    - name: Checkout momo_v3_8
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.8'
        path: 'momo_v3_8'
    - name: Checkout momo_v3_11
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.11'
        path: 'momo_v3_11'
    - name: Checkout momo_cur
      uses: actions/checkout@v4
      with:
        path: 'momo_cur'
    - name: Install Clang
      run: sudo apt install clang-${{ matrix.clang_ver }}
    - name: Build
      run: |
        mkdir build
        clang++-${{ matrix.clang_ver }} -Imomo_v3_2 -O3 -DNDEBUG -std=c++20 -o build/momo_${{ matrix.type }}_1 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_v3_5 -O3 -DNDEBUG -std=c++20 -o build/momo_${{ matrix.type }}_2 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_v3_8/include -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_3 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_v3_11/include -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_4 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_cur/include -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_0 src/momo_${{ matrix.type }}.cc
    - name: Test
      run: |
        sudo nice -n-20 ionice -c1 -n0 sudo -u $USER python3 momo_${{ matrix.type }}.py
