name: Perf Clang

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
        
        - type: 'unordered_map'
          clang_ver: '15'

        - type: 'unordered_map_open'
          clang_ver: '15'

        - type: 'map'
          clang_ver: '15'

        - type: 'data_table_static'
          clang_ver: '15'

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout hash-table-shootout
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/hash-table-shootout'
        ref: 'regress'
    - name: Checkout momo_v32
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.2'
        path: 'momo_v32'
    - name: Checkout momo_v35
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.5'
        path: 'momo_v35'
    - name: Checkout momo_v37
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.7'
        path: 'momo_v37'
    - name: Checkout momo_v39
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.9'
        path: 'momo_v39'
    - name: Checkout momo_cur
      uses: actions/checkout@v4
      with:
        path: 'momo_cur'
    - name: Setup Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.clang_ver }}
    - name: Build
      run: |
        mkdir build
        clang++-${{ matrix.clang_ver }} -Imomo_v32 -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_1 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_v35 -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_2 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_v37 -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_3 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_v39/include -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_4 src/momo_${{ matrix.type }}.cc
        clang++-${{ matrix.clang_ver }} -Imomo_cur/include -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_0 src/momo_${{ matrix.type }}.cc
    - name: Test
      run: |
        sudo nice -n-20 ionice -c1 -n0 sudo -u $USER python3 momo_${{ matrix.type }}.py
