name: Perf Clang

on: [push, pull_request]

jobs:
  momo-perf:
    strategy:
      matrix:
        include:
        
        - type: 'unordered_map'
          clang_ver: '18'

        - type: 'unordered_map_open'
          clang_ver: '18'

        - type: 'map'
          clang_ver: '18'

        - type: 'data_table_static'
          clang_ver: '18'

    runs-on: macos-15

    steps:
    - name: Checkout hash-table-shootout
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/hash-table-shootout'
        ref: 'regress'
    - name: Checkout momo_v3_2
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.2'
        path: 'momo_v3_2'
    - name: Checkout momo_v3_5
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.5'
        path: 'momo_v3_5'
    - name: Checkout momo_v3_7
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.7'
        path: 'momo_v3_7'
    - name: Checkout momo_v3_10
      uses: actions/checkout@v4
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.10'
        path: 'momo_v3_10'
    - name: Checkout momo_cur
      uses: actions/checkout@v4
      with:
        path: 'momo_cur'
    - name: Install Clang
      run: brew install llvm@${{ matrix.clang_ver }}
    - name: Build
      run: |
        mkdir build
        /opt/homebrew/opt/llvm@${{ matrix.clang_ver }}/bin/clang++ -Imomo_v3_2 -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_1 src/momo_${{ matrix.type }}.cc
        /opt/homebrew/opt/llvm@${{ matrix.clang_ver }}/bin/clang++ -Imomo_v3_5 -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_2 src/momo_${{ matrix.type }}.cc
        /opt/homebrew/opt/llvm@${{ matrix.clang_ver }}/bin/clang++ -Imomo_v3_7 -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_3 src/momo_${{ matrix.type }}.cc
        /opt/homebrew/opt/llvm@${{ matrix.clang_ver }}/bin/clang++ -Imomo_v3_10/include -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_4 src/momo_${{ matrix.type }}.cc
        /opt/homebrew/opt/llvm@${{ matrix.clang_ver }}/bin/clang++ -Imomo_cur/include -O3 -DNDEBUG -std=c++23 -o build/momo_${{ matrix.type }}_0 src/momo_${{ matrix.type }}.cc
    - name: Test
      run: python3 momo_${{ matrix.type }}.py
