name: Perf GCC

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
        
        - type: 'unordered_map'
          gcc_ver: '12'

        - type: 'unordered_map_open'
          gcc_ver: '12'

        - type: 'map'
          gcc_ver: '12'

        - type: 'data_table_static'
          gcc_ver: '12'

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout hash-table-shootout
      uses: actions/checkout@v3
      with:
        repository: 'morzhovets/hash-table-shootout'
        ref: 'regress'
    - name: Checkout momo_v32
      uses: actions/checkout@v3
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.2'
        path: 'momo_v32'
    - name: Checkout momo_v35
      uses: actions/checkout@v3
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.5'
        path: 'momo_v35'
    - name: Checkout momo_v37
      uses: actions/checkout@v3
      with:
        repository: 'morzhovets/momo'
        ref: 'v3.7'
        path: 'momo_v37'
    - name: Checkout momo_cur
      uses: actions/checkout@v3
      with:
        path: 'momo_cur'
    - name: Install GCC
      run: sudo apt install g++-${{ matrix.gcc_ver }}
    - name: Build
      run: |
        mkdir build
        g++-${{ matrix.gcc_ver }} -Imomo_v32 -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_v32 src/momo_${{ matrix.type }}.cc
        g++-${{ matrix.gcc_ver }} -Imomo_v35 -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_v35 src/momo_${{ matrix.type }}.cc
        g++-${{ matrix.gcc_ver }} -Imomo_v37 -O3 -DNDEBUG -march=native -std=c++17 -o build/momo_${{ matrix.type }}_v37 src/momo_${{ matrix.type }}.cc
        g++-${{ matrix.gcc_ver }} -Imomo_cur/include -O3 -DNDEBUG -march=native -std=c++20 -o build/momo_${{ matrix.type }}_cur src/momo_${{ matrix.type }}.cc
    - name: Test
      run: |
        sudo nice -n-20 ionice -c1 -n0 sudo -u $USER python3 momo_${{ matrix.type }}.py
